### ISSUE TITLE
Remove built-in opacity in favour of recommending hyper-opacity

### ISSUE THREAD

**Issue by kitten** [pbomb/hyper-night-owl#1]
I'm personally not a big fan of terminal themes with opacity and I'd guess several others aren't either. It's a relatively straightforward piece of code to make Hyper slightly transparent, but there's also `hyper-opacity`:

https://hyper.is/plugins/hyper-opacity

As a conclusion, I don't think there's any need to include it by default in this theme and the readme could instead recommend this plugin instead :wink:

**Comment by pbomb** [comment]
Nice, I wasn't aware of this plugin. I just pushed a change that removes the transparent background by default, with a specify property to enable it, but using the existing plugin you mentioned, which I wasn't aware of, is a better option. Getting ready to push changes to satisfy this suggestion. Thanks!
