### ISSUE TITLE
Publish the theme to hyper store : )

### ISSUE THREAD

**Issue by markozxuu** [pbomb/hyper-night-owl#2]
Hi 😸 👋 

I am a collaborator of **hyper** and **hyper-site**. The theme that he made seems very valuable to me, it should be in a [hyper store](https://github.com/zeit/hyper-site) so that everyone can see it.

These are the [steps](https://github.com/zeit/hyper-site/wiki/Submitting-a-new-plugin-or-theme-to-Hyper-Store) to publish your theme. If you have questions or problems, let me know. I will be happy to help you.

Have a good day ❤️ 🙉

**Comment by pbomb** [comment]
Great suggestion! I'll do that today.

**Comment by pbomb** [comment]
Created pull request [https://github.com/zeit/hyper-site/pull/56](https://github.com/zeit/hyper-site/pull/56).
