### ISSUE TITLE
Remove git and branch in prompt

### ISSUE THREAD

**Issue by realph** [pbomb/hyper-night-owl#4]
Is there an easy way to configure this theme to remove "git" and the "branch name" in the prompt?

![image](https://user-images.githubusercontent.com/2334951/43368508-f29486e2-9355-11e8-8464-ab2c656f00fe.png)

I want it to read:

    -> project

instead of:

    -> project git:(master)

**Comment by pbomb** [comment]
Hi @realph. This plugin does not actually change the prompt text at all. It only affects the colors. There's likely a different hyper plugin you're using that is configuring the prompt for you.

**Comment by pbomb** [comment]
Closing since this doesn't appear to be an issue with this hyper plugin. Please re-open this issue if you determine otherwise.
